import { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import ExportButton from "@/components/ExportButton";
import RiskScoreCard from "@/components/RiskScoreCard";
import AIExplanation from "@/components/AIExplanation";
import MitreTable from "@/components/MitreTable";
import PermissionTable from "@/components/PermissionTable";
import { AnalysisResult } from "@/lib/types";
import { Shield, ArrowLeft, Calendar, Hash, Package } from "lucide-react";

const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";

async function getReport(hash: string): Promise<AnalysisResult | null> {
  try {
    // Try by SHA256 hash → report endpoint
    const res = await fetch(`${API_BASE}/api/analysis/${hash}`, {
      next: { revalidate: 3600 },
    });
    if (res.ok) return res.json();
    // Fallback: report endpoint
    const res2 = await fetch(`${API_BASE}/api/report/${hash}`, {
      next: { revalidate: 3600 },
      headers: { Accept: "application/json" },
    });
    if (res2.ok) return res2.json();
    return null;
  } catch {
    return null;
  }
}

export async function generateMetadata({
  params,
}: {
  params: { hash: string };
}): Promise<Metadata> {
  const report = await getReport(params.hash);
  if (!report) return { title: "Report Not Found — DroidRaksha" };

  const pkg = report.manifest?.package_name || "Unknown App";
  const score = report.risk?.score ?? 0;
  const level = report.risk?.risk_level || "UNKNOWN";
  const description = `DroidRaksha threat analysis for ${pkg}. Risk Score: ${score}/100 (${level}). Generated by India's AI-Powered APK Threat Intelligence Platform.`;

  return {
    title: `${pkg} — DroidRaksha Threat Report`,
    description,
    openGraph: {
      title: `🛡️ DroidRaksha: ${pkg} — Risk Score ${score}/100`,
      description,
      type: "article",
      images: [
        {
          url: `${process.env.NEXT_PUBLIC_FRONTEND_URL || "http://localhost:3000"}/og-report.png`,
          width: 1200,
          height: 630,
          alt: `DroidRaksha report for ${pkg}`,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: `🛡️ ${pkg} — Risk Score ${score}/100`,
      description,
    },
  };
}

const riskColors: Record<string, string> = {
  CRITICAL: "text-rose-400 border-rose-500/40 bg-rose-500/10",
  HIGH: "text-orange-400 border-orange-500/40 bg-orange-500/10",
  MEDIUM: "text-yellow-400 border-yellow-500/40 bg-yellow-500/10",
  LOW: "text-emerald-400 border-emerald-500/40 bg-emerald-500/10",
  SAFE: "text-green-400 border-green-500/40 bg-green-500/10",
};

export default async function ReportPage({
  params,
}: {
  params: { hash: string };
}) {
  const report = await getReport(params.hash);
  if (!report) notFound();

  const pkg = report.manifest?.package_name || "Unknown App";
  const score = report.risk?.score ?? 0;
  const level = report.risk?.risk_level || "UNKNOWN";
  const riskClass = riskColors[level] || "text-slate-200 border-slate-500/30 bg-slate-500/10";
  const createdAt = report.created_at
    ? new Date(report.created_at).toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })
    : "Unknown";

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100">
      {/* Top Bar */}
      <header className="border-b border-slate-800/60 bg-slate-900/80 backdrop-blur-sm sticky top-0 z-40">
        <div className="max-w-6xl mx-auto px-6 py-3 flex items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <Link
              href="/"
              className="flex items-center gap-1.5 text-sm text-slate-200 hover:text-slate-200 transition-colors"
            >
              <ArrowLeft className="w-4 h-4" />
              Back
            </Link>
            <span className="text-slate-300">|</span>
            <div className="flex items-center gap-2">
              <Shield className="w-5 h-5 text-indigo-400" />
              <span className="font-bold text-slate-100 tracking-tight">DroidRaksha</span>
            </div>
          </div>
          <ExportButton
            analysisId={report.id}
            packageName={pkg}
            sha256={report.hashes?.sha256}
          />
        </div>
      </header>

      {/* Hero / Meta Banner */}
      <div className="border-b border-slate-800/40 bg-gradient-to-b from-slate-900 to-slate-950">
        <div className="max-w-6xl mx-auto px-6 py-10">
          {/* Forensic Case Badge */}
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-indigo-500/10 border border-indigo-500/25 text-indigo-300 text-xs font-semibold tracking-wider uppercase mb-6">
            <Shield className="w-3.5 h-3.5" />
            Forensic Analysis Report · DroidRaksha v2.0
          </div>

          <h1 className="text-3xl font-extrabold tracking-tight text-secondary mb-2 break-all">
            {pkg}
          </h1>

          <div className="flex flex-wrap items-center gap-4 mt-4 text-sm text-slate-200">
            <span className={`px-3 py-1 rounded-full border font-bold text-base ${riskClass}`}>
              {level} — {score}/100
            </span>
            <span className="flex items-center gap-1.5">
              <Calendar className="w-4 h-4" />
              {createdAt} IST
            </span>
            {report.hashes?.sha256 && (
              <span className="flex items-center gap-1.5 font-mono text-xs text-slate-300">
                <Hash className="w-3.5 h-3.5" />
                {report.hashes.sha256.slice(0, 20)}…
              </span>
            )}
            {report.filename && (
              <span className="flex items-center gap-1.5">
                <Package className="w-4 h-4" />
                {report.filename}
              </span>
            )}
          </div>

          {/* Chain of Custody Box */}
          <div className="mt-6 rounded-xl border border-slate-700/50 bg-slate-800/40 p-4 grid grid-cols-1 sm:grid-cols-3 gap-4 text-xs text-slate-200">
            <div>
              <div className="text-slate-300 uppercase tracking-wider mb-1">File SHA-256</div>
              <div className="font-mono text-slate-300 break-all text-[11px]">{report.hashes?.sha256 || "N/A"}</div>
            </div>
            <div>
              <div className="text-slate-300 uppercase tracking-wider mb-1">File MD5</div>
              <div className="font-mono text-slate-300 break-all">{report.hashes?.md5 || "N/A"}</div>
            </div>
            <div>
              <div className="text-slate-300 uppercase tracking-wider mb-1">File Size</div>
              <div className="font-mono text-slate-300">
                {report.hashes?.file_size
                  ? `${(report.hashes.file_size / 1024 / 1024).toFixed(2)} MB`
                  : "N/A"}
              </div>
            </div>
          </div>

          {/* Methodology note */}
          <p className="mt-4 text-xs text-slate-300 leading-relaxed max-w-3xl">
            <strong className="text-slate-200">Methodology:</strong> This report was generated by DroidRaksha using
            Androguard static analysis, YARA signature matching (50+ rules), VirusTotal/AbuseIPDB/India-IOC
            threat intelligence enrichment, obfuscation heuristics, and Claude AI narrative generation.
            All findings are based on static analysis of the submitted APK file.
          </p>
        </div>
      </div>

      {/* Content */}
      <main className="max-w-6xl mx-auto px-6 py-10 space-y-8">
        {/* Risk + AI side by side */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <RiskScoreCard risk={report.risk} />
          <AIExplanation
            narrative={report.ai_narrative}
            recommendations={report.ai_recommendations}
          />
        </div>

        {/* MITRE ATT&CK */}
        {report.mitre && report.mitre.length > 0 && (
          <MitreTable tactics={report.mitre} />
        )}

        {/* Permissions */}
        {report.manifest && (
          <PermissionTable
            permissions={report.manifest.permissions}
            dangerousCombos={report.manifest.dangerous_combos}
          />
        )}

        {/* Verdict Footer */}
        <div className="rounded-2xl border border-indigo-500/20 bg-gradient-to-br from-indigo-500/5 to-purple-500/5 p-6">
          <h2 className="text-lg font-bold text-indigo-300 mb-3">⚖️ Forensic Verdict</h2>
          <p className="text-sm text-slate-300 leading-relaxed">
            Based on automated static analysis, this application received a risk score of{" "}
            <strong className="text-secondary">{score}/100</strong> ({level}). The analysis identified
            indicators consistent with{" "}
            {report.risk?.threat_categories?.join(", ") || "potential malicious behavior"}.
            This report may be used as supporting evidence in cybersecurity investigations.
            All findings should be corroborated with dynamic sandbox analysis and human expert review
            before use in formal legal proceedings.
          </p>
          <p className="mt-3 text-xs text-slate-300">
            Generated by DroidRaksha — India&apos;s AI-Powered APK Threat Intelligence Platform ·{" "}
            Report ID: {report.id} · Analysis Date: {createdAt} IST
          </p>
        </div>
      </main>

      <footer className="border-t border-slate-800/40 py-6 text-center text-xs text-slate-200">
        DroidRaksha · Built for India&apos;s cybersecurity ecosystem ·{" "}
        <span className="text-slate-300">For investigative use only</span>
      </footer>
    </div>
  );
}
