"""Initial schema

Revision ID: afb8b98ccdb8
Revises: 
Create Date: 2026-06-26 00:54:58.995276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afb8b98ccdb8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'result_json')
    op.drop_column('pcap_analyses', 'result_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pcap_analyses', sa.Column('result_json', sa.TEXT(), nullable=False))
    op.add_column('analyses', sa.Column('result_json', sa.TEXT(), nullable=False))
    # ### end Alembic commands ###
